[build]
  base = "frontend/dashboard"
  command = "chmod +x build-with-widget.sh && ./build-with-widget.sh"
  publish = "dist"
  ignore = false

[build.environment]
  VITE_BACKEND_URL = "https://callcenterdock.onrender.com"
  VITE_APP_NAME = "CallDocker"
  VITE_WIDGET_BASE_URL = "https://callcenterdock.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 