services:
  - type: web
    name: calldocker-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.vercel.app
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false 