services:
  - type: web
    name: calldocker-backend
    env: node
    plan: free
    buildCommand: cd backend && npm run prebuild && npm run build
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://callcenterdock-dashboard.vercel.app,https://callcenterdock-widget.vercel.app
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false

  - type: web
    name: calldocker-frontend
    env: static
    plan: free
    buildCommand: cd frontend/dashboard && npm install && npm run build
    staticPublishPath: frontend/dashboard/dist
    envVars:
      - key: NODE_VERSION
        value: 18 