services:
  - type: web
    name: calldocker-backend
    env: node
    plan: free
    buildCommand: npm run build:backend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://callcenterdock-dashboard.vercel.app,https://callcenterdock-widget.vercel.app
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false 